-- =====================================================================
-- FlexiDiet Seed: Danh mục 67 món ăn hệ thống (Pha Elaboration)
-- Khớp 1-1 với 67 nhãn của mô hình YOLOv10m (VietFood67)
-- =====================================================================

USE flexidiet;
SET NAMES utf8mb4;

INSERT INTO dishes (dish_code, name, name_norm, origin, serving_label, is_active)
VALUES
  ('banh_canh', 'Bánh canh', 'banh canh', 'system', '1 tô', 1),
  ('banh_chung', 'Bánh chưng', 'banh chung', 'system', '1 cái', 1),
  ('banh_cuon', 'Bánh cuốn', 'banh cuon', 'system', '1 đĩa', 1),
  ('banh_khot', 'Bánh khọt', 'banh khot', 'system', '1 đĩa', 1),
  ('banh_mi', 'Bánh mì', 'banh mi', 'system', '1 ổ', 1),
  ('banh_trang', 'Bánh tráng', 'banh trang', 'system', '100g', 1),
  ('banh_trang_tron', 'Bánh tráng trộn', 'banh trang tron', 'system', '1 phần', 1),
  ('banh_xeo', 'Bánh xèo', 'banh xeo', 'system', '1 cái', 1),
  ('bo_kho', 'Bò kho', 'bo kho', 'system', '1 tô', 1),
  ('bo_la_lot', 'Bò lá lốt', 'bo la lot', 'system', '1 phần', 1),
  ('bong_cai', 'Bông cải', 'bong cai', 'system', '100g', 1),
  ('bun', 'Bún tươi', 'bun tuoi', 'system', '100g', 1),
  ('bun_bo_hue', 'Bún bò Huế', 'bun bo hue', 'system', '1 tô', 1),
  ('bun_cha', 'Bún chả', 'bun cha', 'system', '1 suất', 1),
  ('bun_dau', 'Bún đậu mắm tôm', 'bun dau mam tom', 'system', '1 suất', 1),
  ('bun_mam', 'Bún mắm', 'bun mam', 'system', '1 tô', 1),
  ('bun_rieu', 'Bún riêu', 'bun rieu', 'system', '1 tô', 1),
  ('ca', 'Cá', 'ca', 'system', '100g', 1),
  ('ca_chua', 'Cà chua', 'ca chua', 'system', '100g', 1),
  ('ca_phao', 'Cà pháo', 'ca phao', 'system', '100g', 1),
  ('ca_rot', 'Cà rốt', 'ca rot', 'system', '100g', 1),
  ('canh', 'Canh', 'canh', 'system', '1 bát', 1),
  ('cha', 'Chả lụa', 'cha lua', 'system', '100g', 1),
  ('cha_gio', 'Chả giò (Nem rán)', 'cha gio nem ran', 'system', '1 đĩa', 1),
  ('chanh', 'Chanh', 'chanh', 'system', '1 quả', 1),
  ('com', 'Cơm trắng', 'com trang', 'system', '1 bát', 1),
  ('com_tam', 'Cơm tấm', 'com tam', 'system', '1 đĩa', 1),
  ('cu_kieu', 'Củ kiệu', 'cu kieu', 'system', '100g', 1),
  ('cua', 'Cua', 'cua', 'system', '100g', 1),
  ('dau_hu', 'Đậu hũ', 'dau hu', 'system', '100g', 1),
  ('dua_chua', 'Dưa chua', 'dua chua', 'system', '100g', 1),
  ('dua_leo', 'Dưa leo', 'dua leo', 'system', '100g', 1),
  ('goi_cuon', 'Gỏi cuốn', 'goi cuon', 'system', '1 phần (3 cuốn)', 1),
  ('hamburger', 'Hamburger', 'hamburger', 'system', '1 cái', 1),
  ('heo_quay', 'Heo quay', 'heo quay', 'system', '100g', 1),
  ('hu_tieu', 'Hủ tiếu', 'hu tieu', 'system', '1 tô', 1),
  ('kho_qua_thit', 'Khổ qua dồi thịt', 'kho qua doi thit', 'system', '1 bát', 1),
  ('khoai_tay_chien', 'Khoai tây chiên', 'khoai tay chien', 'system', '1 phần (100g)', 1),
  ('lau', 'Lẩu', 'lau', 'system', '1 nồi', 1),
  ('long_heo', 'Lòng heo', 'long heo', 'system', '100g', 1),
  ('mi', 'Mì', 'mi', 'system', '100g', 1),
  ('muc', 'Mực', 'muc', 'system', '100g', 1),
  ('nam', 'Nấm', 'nam', 'system', '100g', 1),
  ('oc', 'Ốc', 'oc', 'system', '100g', 1),
  ('ot_chuong', 'Ớt chuông', 'ot chuong', 'system', '100g', 1),
  ('pho', 'Phở', 'pho', 'system', '1 tô', 1),
  ('pho_mai', 'Phô mai', 'pho mai', 'system', '100g', 1),
  ('rau', 'Rau xanh', 'rau xanh', 'system', '100g', 1),
  ('salad', 'Salad', 'salad', 'system', '1 đĩa', 1),
  ('thit_bo', 'Thịt bò', 'thit bo', 'system', '100g', 1),
  ('thit_ga', 'Thịt gà', 'thit ga', 'system', '100g', 1),
  ('thit_heo', 'Thịt heo', 'thit heo', 'system', '100g', 1),
  ('thit_kho', 'Thịt kho', 'thit kho', 'system', '1 phần', 1),
  ('thit_nuong', 'Thịt nướng', 'thit nuong', 'system', '1 phần', 1),
  ('tom', 'Tôm', 'tom', 'system', '100g', 1),
  ('trung', 'Trứng', 'trung', 'system', '1 quả', 1),
  ('xoi', 'Xôi', 'xoi', 'system', '1 bát', 1),
  ('banh_beo', 'Bánh bèo', 'banh beo', 'system', '1 đĩa', 1),
  ('cao_lau', 'Cao lầu', 'cao lau', 'system', '1 tô', 1),
  ('mi_quang', 'Mì Quảng', 'mi quang', 'system', '1 tô', 1),
  ('com_chien_duong_chau', 'Cơm chiên Dương Châu', 'com chien duong chau', 'system', '1 đĩa', 1),
  ('bun_cha_ca', 'Bún chả cá', 'bun cha ca', 'system', '1 tô', 1),
  ('com_chien_ga', 'Cơm chiên gà', 'com chien ga', 'system', '1 đĩa', 1),
  ('chao_long', 'Cháo lòng', 'chao long', 'system', '1 tô', 1),
  ('nom_hoa_chuoi', 'Nộm hoa chuối', 'nom hoa chuoi', 'system', '1 đĩa', 1),
  ('nui_xao_bo', 'Nui xào bò', 'nui xao bo', 'system', '1 đĩa', 1),
  ('sup_cua', 'Súp cua', 'sup cua', 'system', '1 bát', 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_norm = VALUES(name_norm),
  serving_label = VALUES(serving_label),
  is_active = VALUES(is_active);
